### PR TITLE
Add save() and saves()

### PR DESCRIPTION
**Pull request by clarkli86**
Support serialising settings into a string or a file.

### CODE REVIEW

**Comment by Grk0** [comment]
Thanks a lot for your interest in this library and for your pull request. Adding a save functionality sounds like a great idea!

Your approach looks good, I just have a couple of small nitpicks:
* The saving functions in the `json` module are called `dump()` and `dumps()`. I'd prefer to stick with that convention.
* Boolean data types are not supported
* Strings need proper sanitation (for backslashes and double quotes)
* Integers greater than `2**31 - 1` or smaller than `-2**31` should get an "L" suffix. While this isn't strictly necessary for libconfig 1.5, it's probably a good idea to support earlier library versions.
* Python 2.7 test failures, see [Travis report](https://travis-ci.org/Grk0/python-libconf/builds/162551941) about the PR. This could be a bit hairy to support due to the type system differences (str/bytes/unicode, int/long). A quick Python3 check as [described here](http://python3porting.com/differences.html#long) would probably be enough.
* I'd prefer dumps() to be implemented on top of dump()+StringIO(). All those string joins using `+=` are a performance killer in Python, as every "`+`" will copy the whole string. `dump()` would just directly `write()` into the supplied file object.

I know it looks like quite a list, but your code is a really good start. I'd prefer to get this fully right instead of incrementally adapting corner cases over the next months.

Would you have the time to come up with another PR incorporating those changes? Otherwise, I can also look into it, taking your code as starting point.

Again, thanks a lot for your effort  :-)

**Comment by clarkli86** [comment]
Hi @Grk0 ,

Thanks for creating this wonderful library. I was mainly using this library with python3 code so backward compatibility was not considered much :-)

Your feedback is very much appreciated. Just not sure what you meant by

> Boolean data types are not supported


Cheers

**Comment by Grk0** [comment]
Thanks a lot for the updated PR! I'll try to look into it over the weekend.

> Boolean data types are not supported

Libconfig can read/write [boolean values](http://www.hyperrealm.com/libconfig/libconfig_manual.html#Boolean-Values). Python-libconf supports reading true/false values as well, it would be good to support writing them too.

**Comment by eatsan** [comment]
any plan to pull this request soon to master? I am planning to start something new soon and dump() is quite relevant to me as well. Thanks for the great work to all of you!

**Comment by Grk0** [comment]
@eatsan : It's a relatively big change and I want to take the time to properly review this. From a quick look, it didn't quite work on Python 2.7, but I should be able to fix this locally.

I'm looking into it now, may take a few days, though. 

Also, thanks a lot for the kind words :-)

**Comment by eatsan** [comment]
Thanks for your quick response. I have one comment. I am already using the branch from @clarkli86 for the initial tests. It seems to be fine for my use-case, however I observed that the ordering of the dumped config changes from the input one. I have the impression this is due to the dict data structure used internally (https://docs.python.org/2/library/stdtypes.html#dict). Am I correct? Although it is not a must-have for my use case, I believe it would be nice to keep the same order if possible. What do you think?

**Comment by Grk0** [comment]
Interesting idea @eatsan. We are already using a custom dictionary (AttrDict, for `d.some_key` syntax instead of `d['some_key']`, so it probably wouldn't be too hard to inherit from `OrderedDict` as well to preserve the item order. I'll look into it.

**Comment by Grk0** [comment]
Thanks a lot @clarkli86 , I've merged your changes.
@eatsan: I've closed  this PR, but I still have the ``OrderedDict`` idea you mentioned on my TODO list. I want to look into that and add proper unicode handling, then I'll push out a new version.

**Comment by clarkli86** [comment]
Thanks @Grk0 for your great work!

**Comment by Grk0** [comment]
@clarkli86, @eatsan: I just pushed libconf 1.0.0 onto PyPI. It includes the dump() logic and the OrderedDict idea to keep the order of configuration options intact.

Thanks again for the PR and the valuable input!

**Comment by clarkli86** [comment]
@Grk0 Thanks again for creating this wonderful library!

**Pull request merged**
